### ISSUE TITLE
Test fails to install on Ubuntu 15.10 clean install in VM environment, with errors

### ISSUE THREAD

**Issue by PeterDCarter** [yjcxy12/ProductSelection#1]
Clean install of Ubuntu 15.10 on a VMWare Workstation Player 12.10 virtual machine; tech test fails with the following error(s):

root@ubuntu:/tech/ProductSelection# npm run test

> productselection@0.1.0 pretest /tech/ProductSelection
> npm run lint

> productselection@0.1.0 lint /tech/ProductSelection
> node_modules/eslint/bin/eslint.js .

sh: 1: node_modules/eslint/bin/eslint.js: not found

npm ERR! productselection@0.1.0 lint: `node_modules/eslint/bin/eslint.js .`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the productselection@0.1.0 lint script.
npm ERR! This is most likely a problem with the productselection package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/eslint/bin/eslint.js .
npm ERR! You can get their info via:
npm ERR!     npm owner ls productselection
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "lint"
npm ERR! cwd /tech/ProductSelection
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tech/ProductSelection/npm-debug.log
npm ERR! not ok code 0

npm ERR! productselection@0.1.0 pretest: `npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the productselection@0.1.0 pretest script.
npm ERR! This is most likely a problem with the productselection package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint
npm ERR! You can get their info via:
npm ERR!     npm owner ls productselection
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
npm ERR! cwd /tech/ProductSelection
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tech/ProductSelection/npm-debug.log
npm ERR! not ok code 0

**Comment by PeterDCarter** [comment]
Update: running an ```apt-get install nodejs-legacy``` to install the legacy version of node, then running ```npm install``` again, followed by the ```npm run test``` command appears to partially resolve the error, with installation now failing with only the following message(s):

npm ERR! productselection@0.1.0 test: `_mocha tests/**/*-tests.js -r babel-core/register -r babel-polyfill`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the productselection@0.1.0 test script.
npm ERR! This is most likely a problem with the productselection package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     _mocha tests/**/*-tests.js -r babel-core/register -r babel-polyfill
npm ERR! You can get their info via:
npm ERR!     npm owner ls productselection
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
npm ERR! cwd /tech/ProductSelection
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tech/ProductSelection/npm-debug.log
npm ERR! not ok code 0

**Comment by yjcxy12** [comment]
It seems that eslint cannot be found. Have you run `npm install` first?

**Comment by PeterDCarter** [comment]
Yes.

**Comment by yjcxy12** [comment]
It seems that this is due to nodejs version is too low. As you can see in [travis](https://travis-ci.org/yjcxy12/ProductSelection), it only succeeds on node version higher than v4. 

Can you try install latest [nodejs](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) and try again?

**Comment by PeterDCarter** [comment]
Ah-ha! Had run ```npm install node``` and ```npm update node``` but it appears from further research more is required. Am running full node version update now...

**Comment by PeterDCarter** [comment]
Have run full update to the latest available version of node. Error remains:

"npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! productselection@0.1.0 test: `_mocha tests/**/*-tests.js -r babel-core/register -r babel-polyfill`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the productselection@0.1.0 test script '_mocha tests/**/*-tests.js -r babel-core/register -r babel-polyfill'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the productselection package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     _mocha tests/**/*-tests.js -r babel-core/register -r babel-polyfill
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs productselection
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls productselection
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tech/ProductSelection/npm-debug.log"

**Comment by PeterDCarter** [comment]
npm-deb.log shows the following:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle productselection@0.1.0~pretest: productselection@0.1.0
6 verbose lifecycle productselection@0.1.0~pretest: unsafe-perm in lifecycle true
7 verbose lifecycle productselection@0.1.0~pretest: PATH: /usr/lib/node_modules/$
8 verbose lifecycle productselection@0.1.0~pretest: CWD: /tech/ProductSelection
9 silly lifecycle productselection@0.1.0~pretest: Args: [ '-c', 'npm run lint' ]
10 silly lifecycle productselection@0.1.0~pretest: Returned: code: 0  signal: nu$
11 info lifecycle productselection@0.1.0~test: productselection@0.1.0
12 verbose lifecycle productselection@0.1.0~test: unsafe-perm in lifecycle true
13 verbose lifecycle productselection@0.1.0~test: PATH: /usr/lib/node_modules/np$
14 verbose lifecycle productselection@0.1.0~test: CWD: /tech/ProductSelection
15 silly lifecycle productselection@0.1.0~test: Args: [ '-c',
15 silly lifecycle   '_mocha tests/**/*-tests.js -r babel-core/register -r babel$
16 silly lifecycle productselection@0.1.0~test: Returned: code: 1  signal: null
17 info lifecycle productselection@0.1.0~test: Failed to exec test script
18 verbose stack Error: productselection@0.1.0 test: `_mocha tests/**/*-tests.js$
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/$
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at EventEmitter.emit (events.js:185:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/$
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at ChildProcess.emit (events.js:185:7)
18 verbose stack     at maybeClose (internal/child_process.js:850:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_proc$
17 info lifecycle productselection@0.1.0~test: Failed to exec test script
18 verbose stack Error: productselection@0.1.0 test: `_mocha tests/**/*-tests.js$
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/$
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at EventEmitter.emit (events.js:185:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/$
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at ChildProcess.emit (events.js:185:7)
18 verbose stack     at maybeClose (internal/child_process.js:850:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_proc$
19 verbose pkgid productselection@0.1.0
20 verbose cwd /tech/ProductSelection
21 error Linux 4.2.0-34-generic
22 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
23 error node v5.9.0
24 error npm  v3.7.3
25 error code ELIFECYCLE
26 error productselection@0.1.0 test: `_mocha tests/**/*-tests.js -r babel-core/$
26 error Exit status 1
27 error Failed at the productselection@0.1.0 test script '_mocha tests/**/*-tes$
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the productselection pack$
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     _mocha tests/**/*-tests.js -r babel-core/register -r babel-polyfill
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs productselection
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls productselection
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by PeterDCarter** [comment]
Contents of debug log attached.
[npm-debug.log.txt](https://github.com/yjcxy12/ProductSelection/files/181226/npm-debug.log.txt)

**Comment by yjcxy12** [comment]
That's weird. It looks like it doesn't like `/**/*-tests.js` and converts it to `//*-tests.js` which causes issue. I've made a modification on test script that should resolve this issue. 

It'd be great if you can pull latest version and update on the issue.

**Comment by PeterDCarter** [comment]
Will do...

**Comment by PeterDCarter** [comment]
Same error :~/

**Comment by PeterDCarter** [comment]
Do you want me to fix the error in the tech test? I can but it will take me a while. Is there a job at the end of this because I would very much like one :).

**Comment by yjcxy12** [comment]
If you need to, please. I couldn't think of the cause. 

What kind of job are you asking? This repo is in response to Sky tech test. And is done half a day. This is by no means production ready nor has future practical use. Only for a reference I guess. If it's the Sky job you after, it's best to contact their recruiting team. I'm just a candidate :).

**Comment by PeterDCarter** [comment]
A recruitment team pointed me in this direction and said this was the
second phase of their recruitment process. If you want help fixing it up
then I am 100% happy to help. My feeling is that I would rather one of us
got the job than neither and hence I would be more than willing to work as
a team on this if we are both in the running.

**Comment by yjcxy12** [comment]
My recruitment phase has ended. It would be good if this repo has been any help.

**Comment by PeterDCarter** [comment]
I think I may have missed the window :/. Thanks though. If you have other
projects in future just give me a holler

**Comment by PeterDCarter** [comment]
Move to close this issue due to redundancy
